run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - noctx
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  gofmt:
    simplify: true

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
